-- Para garantizar que el grupo administradores tiene todos los permisos
delete from profile where UserGroup=1;
insert into profile (Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, Item, UserGroup) select getdate(), replace(NEWID(),'-',''), getdate(), null, null, 0, getdate(), null, sys_pk, 1 from sitem;

--Para garantizar la existencia de todos los iconos en el panel principal del sistema
delete from ut_homepage;
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'1C8766D1077C4F2B8CCFC77C700078B6',getdate(),NULL,NULL,0,getdate(),NULL,0,'Mi Empresa',NULL,NULL,1,NULL);
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'154BA77BB1E446CAAA00127BC300632E',getdate(),NULL,NULL,0,getdate(),NULL,1,'Tableros de indicadores','icons\\MCBI.jpg','MaxicomercioBI.qTableros()',2,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'25BD2F61161E4F49A8E0D17913EC1FC5',getdate(),NULL,NULL,0,getdate(),NULL,1,'Atención a clientes','icons\\atencion.jpg','UICRM.ShowCRM()',3,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'AC0E2AC278A74489ADE7ABA38100022D',getdate(),NULL,NULL,0,getdate(),NULL,1,'Requisiciones','icons\\requisiciones.jpg','UIRequisiciones.MainRequisiciones()',4,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'312F2B27FCDD4CADB7C4340768DAF54F',getdate(),NULL,NULL,0,getdate(),NULL,1,'Proveedores','icons\\proveedor.jpg','UICxP.QCxP()',5,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'FA380D257C8D423FAFBA151FC39F711D',getdate(),NULL,NULL,0,getdate(),NULL,1,'Compras','icons\\compras.jpg','UICompras.QCompras()',6,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'7ED620A01F9949D6823DE7C8D64E992D',getdate(),NULL,NULL,0,getdate(),NULL,1,'Materias primas','icons\\materiaprima.jpg','UIInventario.QMateriasPrimasXLinea()',7,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'A9CB5FC8AE1F46A8B5D57629FFC0C6D0',getdate(),NULL,NULL,0,getdate(),NULL,1,'Recetas','icons\\recetas.jpg','UIInventario.QRecetasXLinea()',8,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'7C3013BBCB34409FA4E9C81491BA4B90',getdate(),NULL,NULL,0,getdate(),NULL,1,'Artículos y servicios','icons\\inventario.jpg','UIInventario.QProductosXLinea()',9,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'1234BDE4B4B84529A436CF1C84A861FF',getdate(),NULL,NULL,0,getdate(),NULL,1,'Clientes','icons\\cliente.jpg','UICxC.QCxC()',10,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'1558B04EB38B4ACD92D31FE86CDED7E5',getdate(),NULL,NULL,0,getdate(),NULL,1,'Ventas','icons\\ventas.jpg','UIVentas.QVentas()',11,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'699F02FB5E3F4945B4151D95FE74A7F8',getdate(),NULL,NULL,0,getdate(),NULL,1,'Gastos','icons\\credito.jpg','UIGastos.qGastos()',12,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'3FF5E53A742147CCBDC769A3D656FD8B',getdate(),NULL,NULL,0,getdate(),NULL,1,'Promociones','icons\\promociones.JPG',' UIVentas.QPromociones()',13,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'B9A29EE5DF1842AB8E9B5C5F177B8462',getdate(),NULL,NULL,0,getdate(),NULL,1,'Cuentas de Cheques','icons\\chequera.jpg','UIFinanzas.QAdminCuentasCheques()',14,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'9ACB214FFD8840A09B63BF32D1B5789F',getdate(),NULL,NULL,0,getdate(),NULL,1,'Cuentas Contables','icons\\ccontable.jpg','UIFinanzas.qCuentas()',15,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'846C8209079F4C379CA6A231FCB0C4B6',getdate(),NULL,NULL,0,getdate(),NULL,1,'Relacionar Cuentas Contables','icons\\relcta.jpg','UIFinanzas.ShowRelacionaCuentas()',16,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'2D2419CD5EF04845B94E6FF7A55E2216',getdate(),NULL,NULL,0,getdate(),NULL,1,'Pólizas','icons\\polizas.jpg',' UIFinanzas.QPoliza()',17,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'2BFB2A3EDC6F4B88B3AD797B706BA204',getdate(),NULL,NULL,0,getdate(),NULL,1,'Ejercicios Contables','icons\\Archivo.jpg','UIEjercicio.AdministrarEjercicios()',18,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'E8CDA6C6B2354CF2BC7D009D7C05D032',getdate(),NULL,NULL,0,getdate(),NULL,1,'Cortes de Caja','icons\\cortecaja.jpg','UIFinanzas.QSesionesCaja()',19,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'2C436807ACFF4695B8F143F8DB62CB65',getdate(),NULL,NULL,0,getdate(),NULL,1,'Facturación Electrónica','icons\\Facturacion electronica.jpg','cfd.qCFD()',20,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'938564D50D2D420E8224B8ADA3A64982',getdate(),NULL,NULL,0,getdate(),NULL,1,'Panel de Control','icons\\panelcontrol.jpg','FXConfig.AbrirPanelControl()',21,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'9574C3B665B64904A590F9B824A533CE',getdate(),NULL,NULL,0,getdate(),NULL,0,'Mis Empleados',NULL,NULL,22,NULL);
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'2643DA58CF634D22B51906D0D2E18198',getdate(),NULL,NULL,0,getdate(),NULL,1,'Meseros','icons\\mesero1.jpg','DMCatalogos.BrwAgentes()',23,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'A58C094013E44786B957D4F68028C974',getdate(),NULL,NULL,0,getdate(),NULL,1,'Cajeros','icons\\cajero.jpg','Catalogos.BrwCajeros()',24,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'0A51EF276B374CB982C875B7CA128262',getdate(),NULL,NULL,0,getdate(),NULL,1,'Repartidores','icons\\repartidor.jpg','Catalogos.BrwRepartidor()',25,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'A450BDC7B44242A2857C7178BA92A2E4',getdate(),NULL,NULL,0,getdate(),NULL,0,'Mis Catálogos',NULL,NULL,26,NULL);
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'C29360ED367A4642BD56AF664200B0B3',getdate(),NULL,NULL,0,getdate(),NULL,1,'Contactos','icons\\Contactos.jpg','Catalogos.BrwContactos()',27,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'11A82B4D2B5D4CA8B2D3099CD4DE56CA',getdate(),NULL,NULL,0,getdate(),NULL,1,'Centros de producción y consumo','icons\\centro de consumo.jpg','DMCatalogos.dlgCProduccionCConsumo()',28,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'03DBED4D4B2D4F8DB18FC2490534E597',getdate(),NULL,NULL,0,getdate(),NULL,1,'Almacenes','icons\\almacen.jpg','UIInventario.CatalogoAlmacenes()',29,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'EF10BDBA403C44459B00A710C601C873',getdate(),NULL,NULL,0,getdate(),NULL,1,'Líneas de materias primas','icons\\lineamateriasprimas.jpg','DMCatalogos.BrwLineas(1)',30,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'130FF9AA506B4C8BA9A2774BAA8C02D1',getdate(),NULL,NULL,0,getdate(),NULL,1,'Líneas de recetas','icons\\linearecetas.jpg','DMCatalogos.BrwLineas(2)',31,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'A4E3BD7E89BD42B9B1DA1537A7D7F8EA',getdate(),NULL,NULL,0,getdate(),NULL,1,'Líneas de artículos y servicios','icons\\lineas.jpg','DMCatalogos.BrwLineas()',32,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'C072DB2018FC4FC7A3BB47ADAA6303BC',getdate(),NULL,NULL,0,getdate(),NULL,1,'Marcas','icons\\marcas.jpg','UIInventario.CatalogoMarcas()',33,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'C54CEABB80BB47C1817FE40000F625D6',getdate(),NULL,NULL,0,getdate(),NULL,1,'Departamentos','icons\\departamentos.jpg','UIInventario.CatalogoDepartamentos()',34,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'0FC32B4CA39C4B6B9BA0CF49BAAD0062',getdate(),NULL,NULL,0,getdate(),NULL,1,'Categorías','icons\\categorias.jpg',' Catalogos.BrwCategorias(0)',35,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'76CC91F98C3A42949300BB34C6ABD253',getdate(),NULL,NULL,0,getdate(),NULL,1,'Divisas','icons\\divisas.jpg','Catalogos.BrwDivisas()',36,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'3EC90E7275B144D19C40DF2FE11868BD',getdate(),NULL,NULL,0,getdate(),NULL,1,'Bancos','icons\\banco.jpg','Catalogos.BrwBancos()',37,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'63031A2D442340619E4700D7E6E01BC1',getdate(),NULL,NULL,0,getdate(),NULL,1,'Tarjeta de Crédito','icons\\tarjetas.JPG','Catalogos.BrwTarjetacredito()',38,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'33D48DD34AD3428898E9BB73B30033A8',getdate(),NULL,NULL,0,getdate(),NULL,1,'Cajas','icons\\cajas.JPG','Catalogos.BrwCajas()',39,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'FBA8B3C0EFD448CFBB5E4B9000EFDDE5',getdate(),NULL,NULL,0,getdate(),NULL,1,'Zonas','icons\\zonas.jpg','Catalogos.BrwZonas()',40,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'4AC77E40EB5C44238172A711DAC58F65',getdate(),NULL,NULL,0,getdate(),NULL,1,'Países, Estados y Ciudades','icons\\paises.jpg','Paises.ExplorerCountry()',41,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'4227C41AC85A4AE7BEAC027DFBBE2CFC',getdate(),NULL,NULL,0,getdate(),NULL,1,'Configuración de Impuestos','icons\\impuestos.jpg','Catalogos.BrwCfgImpuestos()',42,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'9F3C5E37B1F3432DB16336D0D8B59EAD',getdate(),NULL,NULL,0,getdate(),NULL,1,'Aduanas','icons\\aduanas.jpg','UIGastos.CatalogoAduanas()',43,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'9F4616E442724697A34B4B39E635B77D',getdate(),NULL,NULL,0,getdate(),NULL,1,'Tipos de póliza','icons\\TipoPolizas.jpg','UIFoliosPolizas.ShowBrowser()',44,'*');
INSERT INTO ut_homepage ( Sys_TimeStamp, Sys_GUID, Sys_DTCreated, Sys_User, Sys_LastUser, Sys_Exported, Sys_DTExported, Sys_Info, uf_Tipo, uf_Titulo, uf_Imagen, uf_Funcion, uf_Orden, uf_grupos) Values  (getdate(),'19D9EBB57EA749988FA3BBCD7602C7D1',getdate(),NULL,NULL,0,getdate(),NULL,1,'Porteadores','icons\\porteadores.jpg','Catalogos.BrwPorteador()',45,'*');


--Nuevas
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'DelDOrden') AND type in (N'P', N'PC')) DROP PROCEDURE DelDOrden;
CREATE PROCEDURE DelDOrden AS BEGIN DELETE FROM DOrden; END
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'DelOrden') AND type in (N'P', N'PC')) DROP PROCEDURE DelOrden;
CREATE PROCEDURE DelOrden AS BEGIN DELETE FROM Orden; END
ALTER TABLE cpoliza ALTER  COLUMN Concepto VARCHAR(max) NULL;
ALTER TABLE utdbaccessinfo ALTER  COLUMN db VARCHAR(1000) NULL;